### ISSUE TITLE
Error when running 'sudo python manage.py migrate'

### ISSUE THREAD

**Issue by weslambert** [jbc22/hipara-server#1]
When trying this out, when I get to "sudo python manage.py migrate", I receive the following error:

Running migrations:
  Rendering model states... DONE
  Applying rule_manager.0002_auto_20151202_1245...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 120, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/var/www/so/hipara/rule_manager/migrations/0002_auto_20151202_1245.py", line 10, in data_seeder
    superadmin = User.objects.all()[1]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 297, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

If I try to continue with the install, I eventually get 

(After running "python manage.py runserver 0.0.0.0:8000")

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

However, I encounter the same error when running the recommended command again.  Any thoughts? When I try to login locally with user@hipara.org, I receive a huge error trace in regard to "mysql.django_session" being nonexistent.

Thanks,
Wes

**Comment by kohakade** [comment]
Hi,
  It seems to be server python version is 2.7. but requirement for hipara_server for python version is 3.4   and greater. Also there are some unapplied migrations so try to remove all tables from database and try again.

I recommend  you to start fresh installation with install guide (Python 3.4).

**Comment by weslambert** [comment]
Even after installing python 3.4, issuing a python3.4 -V ( python 3.4.4), and setting "alias python=python2.7" in ~/.bash_aliases, I still received an error when trying to start the server.

python manage.py runserver 0.0.0.0:8000 results in the server starting, but saying I have unapplied migrations that should be applied by running 'python manage.py migrate'.  If I try do so, I get the 'IndexError: list index out of range' error.  If I try to apply the migration using 'python3.4 manage.py migrate', then I get an error about 'No module named 'django''.

If I try to run the server using:

'python3.4 manage.py runserver 0.0.0.0:8000', again, I get the "No module named 'django'"error. 

I will try on a fresh install w/ Python 3.4 to see if I can get it working there.

Thanks,
Wes

**Comment by jbc22** [comment]
Wes - can you do a "pip3 -r /var/so/www/hipara/requirements.txt". I imagine when that was initially ran, it was ran for python2.7. If pip3 is not installed, issue "sudo apt-get install python3-setuptools" if you're on Ubuntu 14.04. If you are on 12.04:

sudo apt-get install python3-setuptools
sudo easy_install3 pip

**Comment by weslambert** [comment]
I confirmed pip3 was installed by running "sudo apt-get install python3-setuptools".  It came back saying pip3 was already installed (Ex. python3-setuptools is already the newest version.)

After running the following: 
pip3 install -r requirements.txt (from /var/www/so/hipara)

I get the same error message(s) when trying to run the commands from the previous post(s).

Thanks,
Wes
